// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TulipHR.API.DbContexts;

#nullable disable

namespace TulipHR.API.Migrations
{
    [DbContext(typeof(OrganizationContext))]
    [Migration("20230501162504_OrgDbInitMigration")]
    partial class OrgDbInitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("TulipHR.API.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            Number = "T0001",
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Smith",
                            Number = "T0002",
                            PositionId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Bob",
                            LastName = "Johnson",
                            Number = "T0003",
                            PositionId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Dave",
                            LastName = "Raynal",
                            Number = "T0004",
                            PositionId = 4
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Michael",
                            LastName = "Song",
                            Number = "T0005",
                            PositionId = 5
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Brett",
                            LastName = "Lee",
                            Number = "T0006",
                            PositionId = 6
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Charles",
                            LastName = "Smith",
                            Number = "T0007",
                            PositionId = 7
                        });
                });

            modelBuilder.Entity("TulipHR.API.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManagerPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagerPositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "1",
                            Title = "Director"
                        },
                        new
                        {
                            Id = 2,
                            ManagerPositionId = 1,
                            Number = "2",
                            Title = "Senior Manager"
                        },
                        new
                        {
                            Id = 3,
                            ManagerPositionId = 2,
                            Number = "3",
                            Title = "Manager 1"
                        },
                        new
                        {
                            Id = 4,
                            ManagerPositionId = 2,
                            Number = "3",
                            Title = "Manager 2"
                        },
                        new
                        {
                            Id = 5,
                            ManagerPositionId = 3,
                            Number = "4",
                            Title = "Senior Developer 1"
                        },
                        new
                        {
                            Id = 6,
                            ManagerPositionId = 4,
                            Number = "4",
                            Title = "Senior Developer 2"
                        },
                        new
                        {
                            Id = 7,
                            ManagerPositionId = 5,
                            Number = "5",
                            Title = "Junior Developer"
                        },
                        new
                        {
                            Id = 8,
                            ManagerPositionId = 6,
                            Number = "5",
                            Title = "Junior Developer"
                        });
                });

            modelBuilder.Entity("TulipHR.API.Entities.Employee", b =>
                {
                    b.HasOne("TulipHR.API.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TulipHR.API.Entities.Position", b =>
                {
                    b.HasOne("TulipHR.API.Entities.Position", "ManagerPosition")
                        .WithMany()
                        .HasForeignKey("ManagerPositionId");

                    b.Navigation("ManagerPosition");
                });
#pragma warning restore 612, 618
        }
    }
}
